server:
  port: 7002

spring:
  datasource:
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:classpath:./variables-local.properties
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    smtp:
      auth: true
      starttls:
        enable: true
